spring.application.name=be-challenge
spring.profiles.active=local
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/be_challenge}

app.s3.bucket=${S3_BUCKET:be-challenge-bucket}
app.s3.region=${AWS_REGION:us-east-1}
app.s3.endpoint=${S3_ENDPOINT:http://localhost:4566}

app.s3.signed-url-expiration-seconds=900