version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

volumes:
  mongo_data: